version: 2.1

orbs:
  terraform: circleci/terraform@1.1.0

jobs:
  format:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout

      - run:
          name: terraform fmt
          command: |
            terraform fmt -check=true

      - persist_to_workspace:
          root: .
          paths:
            - .

  init_and_plan:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout

      - run:
          name: terraform init
          command: |
            echo $region
            terraform init -backend=false

      - run:
          name: terraform validate
          command: |
            terraform validate

      - run:
          name: terraform plan
          command: |
            terraform plan -out moduletest

      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  format_validate_init-plan:
    jobs:
      - format
      - init:
          requires:
            - format
